My Project: VDinamico< T > Class Template Reference
VDinamico< T > Class Template Reference
#include <VDinamico.h>
Public Member Functions
VDinamico ()
constructor por defecto de VDinamico, inicializa todos sus atributos a los valores por defecto especificados
VDinamico (unsigned int tamlog)
constructor parametrizado de VDinamico, al que se le pasará un tamaño logico _tamlog y construira un VDinamico de tamaño fisico _tamfis de la potencia de 2 inmediatamente superior al tamaño logico
VDinamico (const VDinamico< T > &orig)
constructor de copia de VDinamico
VDinamico (const VDinamico< T > &orig, unsigned int posicionInicial, unsigned int numElementos)
constructor de copia parcial de VDinamico, copaiara los valores del VDinamico orig en un intervalo de posiciones determinado por los parametros
VDinamico< T > & operator= (const VDinamico< T > &vec)
operador de asignacion de VDinamico
T & operator[] (unsigned int pos)
operador [] de VDinamico, permite trabajar con cualquier objeto de este tipo usando los corchetes para acceder a el elemento almacenado en la posicion pos
void insertar (const T &dato, unsigned int pos=UINT_MAX)
metodo para insertar datos en un objeto VDinamico
T borrar (unsigned int pos=UINT_MAX)
metodo para borrar datos en un objeto VDinamico
void ordenar ()
ordena el VDinamico utilizando el metodo sort de la libreria algorithm
void ordenarRev ()
ordena el VDinamico de mayor a menor usando el metodo sort de algorithm
int busquedaBin (T &dato)
busqueda de una Imaagen dentro de un VDinamico mediante el algoritmo de la busqueda binaria
unsigned int tamlog ()
metodo para consultar el tamaño logico _tamlog de un VDinamico
virtual ~VDinamico ()
destructor de VDianmico
Static Public Member Functions
static bool mayorQue (T &a, T &b)
metodo que compara dos objetos genericos, necesaria para que ordenaRev funcione con sort
Private Member Functions
void disminuye ()
metodo privado que disminuye el tamaño fisico _tamfis de un VDinamico a la mitad una vez que el tamaño logico _tamlog sea igual a un tercio del _tamfis
void aumenta ()
metodo privado que aumenta el tamaño fisico _tamfis de un VDinamico al doble una vez que el tamaño logico _tamlog sea igual a _tamfis
Private Attributes
unsigned int _tamfis
unsigned int _tamlog
T * v = nullptr
Detailed Description
template<typename T>
class VDinamico< T >
Definition at line 13 of file VDinamico.h.
Constructor & Destructor Documentation
VDinamico() [1/4]
template<typename T > VDinamico< T >::VDinamico
constructor por defecto de VDinamico, inicializa todos sus atributos a los valores por defecto especificados
Template Parameters
T tipo de dato
Definition at line 86 of file VDinamico.h.
VDinamico() [2/4]
template<typename T > VDinamico< T >::VDinamico (unsigned int tamlog) explicit
constructor parametrizado de VDinamico, al que se le pasará un tamaño logico _tamlog y construira un VDinamico de tamaño fisico _tamfis de la potencia de 2 inmediatamente superior al tamaño logico
Template Parameters
T tipo de dato
Parameters
tamlog tamaño logico, es decir, el numero de elementos que se quieren almacenar en el VDinamico
Definition at line 97 of file VDinamico.h.
References VDinamico< T >::_tamfis, and VDinamico< T >::tamlog().
VDinamico() [3/4]
template<typename T > VDinamico< T >::VDinamico (const VDinamico< T > & orig)
constructor de copia de VDinamico
Template Parameters
T tipo de dato
Parameters
orig VDinamico del que se copian sus valores
Definition at line 113 of file VDinamico.h.
References VDinamico< T >::_tamfis, and VDinamico< T >::v.
VDinamico() [4/4]
template<typename T > VDinamico< T >::VDinamico (const VDinamico< T > & orig, unsigned int posicionInicial, unsigned int numElementos)
constructor de copia parcial de VDinamico, copaiara los valores del VDinamico orig en un intervalo de posiciones determinado por los parametros
Template Parameters
T tipo de dato
Parameters
orig Vdinamico del que se quiere copiar
posicionInicial posicion del VDinamico desde la que se quiere copiar valores
numElementos numero de elementos del VDinamico que queremos copiar
Exceptions
std::invalid_argument si se le pasa alguna posicionInicial o numElementos que supere el tamaño fisico _tamfis
Definition at line 129 of file VDinamico.h.
References VDinamico< T >::v.
~VDinamico()
template<typename T > VDinamico< T >::~VDinamico virtual
destructor de VDianmico
Template Parameters
T tipo de dato
Definition at line 287 of file VDinamico.h.
Member Function Documentation
aumenta()
template<typename T > void VDinamico< T >::aumenta private
metodo privado que aumenta el tamaño fisico _tamfis de un VDinamico al doble una vez que el tamaño logico _tamlog sea igual a _tamfis
Template Parameters
T tipo de dato
Definition at line 72 of file VDinamico.h.
borrar()
template<typename T > T VDinamico< T >::borrar (unsigned int pos = UINT_MAX)
metodo para borrar datos en un objeto VDinamico
Template Parameters
T tipo de dato
Parameters
pos posicion del elemento que se quiere borrar
Returns
el elemento borrado del VDinamico
Exceptions
std::invalid_argument si se introduce una posicion pos incorrecta
Definition at line 208 of file VDinamico.h.
Referenced by recuperaImgs().
busquedaBin()
template<typename T > int VDinamico< T >::busquedaBin (T & dato)
busqueda de una Imaagen dentro de un VDinamico mediante el algoritmo de la busqueda binaria
Precondition
el ContenedorImagenes debe estar ordenado habiendose usdado el correspondiente metodo ordenar()
Returns
la posicion del elemento buscado en el ContenedorImagenes
Definition at line 257 of file VDinamico.h.
Referenced by main().
disminuye()
template<typename T > void VDinamico< T >::disminuye private
metodo privado que disminuye el tamaño fisico _tamfis de un VDinamico a la mitad una vez que el tamaño logico _tamlog sea igual a un tercio del _tamfis
Template Parameters
T tipo de dato
Definition at line 58 of file VDinamico.h.
insertar()
template<typename T > void VDinamico< T >::insertar (const T & dato, unsigned int pos = UINT_MAX)
metodo para insertar datos en un objeto VDinamico
Template Parameters
T tipo de dato
Parameters
dato elemento a insertar en el VDinamico
pos posicion en la que se insertará el elemento dato
Exceptions
std::invalid_argument si se introduce una posicion pos incorrecta
Definition at line 184 of file VDinamico.h.
Referenced by main(), and recuperaImgs().
mayorQue()
template<typename T > bool VDinamico< T >::mayorQue (T & a, T & b) static
metodo que compara dos objetos genericos, necesaria para que ordenaRev funcione con sort
Parameters
a primer objeto que se quiere comparar
b segundo objeto que se quiere comparar
Template Parameters
T tipo de dato
Returns
valor booleano true si a es mayor que b y false en cualquier otro caso
Definition at line 239 of file VDinamico.h.
operator=()
template<typename T > VDinamico< T > & VDinamico< T >::operator= (const VDinamico< T > & vec)
operador de asignacion de VDinamico
Template Parameters
T tipo de dato
Parameters
vec VDinamico en el que queremos asignar
Returns
puntero al VDinamico al que se le asignan los datos
Definition at line 153 of file VDinamico.h.
References VDinamico< T >::_tamfis, VDinamico< T >::_tamlog, and VDinamico< T >::v.
operator[]()
template<typename T > T & VDinamico< T >::operator[] (unsigned int pos)
operador [] de VDinamico, permite trabajar con cualquier objeto de este tipo usando los corchetes para acceder a el elemento almacenado en la posicion pos
Template Parameters
T tipo de dato
Parameters
pos posicion de v* de la cual se quiere consultar su contendido
Returns
v[pos] el elemento alamcenado en la posicion pos que se pasa como parametro
Definition at line 173 of file VDinamico.h.
ordenar()
template<typename T > void VDinamico< T >::ordenar
ordena el VDinamico utilizando el metodo sort de la libreria algorithm
Template Parameters
T tipo de dato
Definition at line 228 of file VDinamico.h.
Referenced by main().
ordenarRev()
template<typename T > void VDinamico< T >::ordenarRev
ordena el VDinamico de mayor a menor usando el metodo sort de algorithm
Template Parameters
T tipo de dato
Definition at line 247 of file VDinamico.h.
Referenced by main().
tamlog()
template<typename T > unsigned int VDinamico< T >::tamlog
metodo para consultar el tamaño logico _tamlog de un VDinamico
Template Parameters
T tipo de dato
Returns
_tamlog tamaño logico del objeto VDinamico
Definition at line 279 of file VDinamico.h.
Referenced by main(), recuperaImgs(), and VDinamico< T >::VDinamico().
Member Data Documentation
_tamfis
template<typename T > unsigned int VDinamico< T >::_tamfis private
Definition at line 15 of file VDinamico.h.
Referenced by VDinamico< T >::operator=(), and VDinamico< T >::VDinamico().
_tamlog
template<typename T > unsigned int VDinamico< T >::_tamlog private
Definition at line 16 of file VDinamico.h.
Referenced by VDinamico< T >::operator=().
v
template<typename T > T* VDinamico< T >::v = nullptr private
Definition at line 17 of file VDinamico.h.
Referenced by VDinamico< T >::operator=(), and VDinamico< T >::VDinamico().
The documentation for this class was generated from the following file:
VDinamico.h