My Project: main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <ctime>
#include "Imagen.h"
#include "VDinamico.h"
Functions
void recuperaImgs (VDinamico< Imagen > &vec, string correo, VDinamico< Imagen > &vnuevo)
recupera un numero de imagenes determinado por el usuario conociendo el email que figura en el atributo email de esta y el vector donde estan contenidas estas, y las asigna a un nuevo ContenedorImagenes
int main ()
Function Documentation
main()
int main ()
Definition at line 29 of file main.cpp.
References Fecha::asignarDia(), VDinamico< T >::busquedaBin(), VDinamico< T >::insertar(), VDinamico< T >::ordenar(), VDinamico< T >::ordenarRev(), recuperaImgs(), Imagen::setEmail(), Imagen::setEtiquetas(), Imagen::setFecha(), Imagen::setId(), Imagen::setNombre(), Imagen::setTam(), and VDinamico< T >::tamlog().
recuperaImgs()
void recuperaImgs (VDinamico< Imagen > & vec, string correo, VDinamico< Imagen > & vnuevo)
recupera un numero de imagenes determinado por el usuario conociendo el email que figura en el atributo email de esta y el vector donde estan contenidas estas, y las asigna a un nuevo ContenedorImagenes
Author
Manuel Lara Torres mlt00.nosp@m.024@.nosp@m.red.u.nosp@m.jaen.nosp@m..es
Parameters
num numero de imagenes a recuperar
email cadena de caracteres que quieres buscar en la imagen
vectorOrigen vector donde estan almacenadas las imgs
anio anio en el que se tomaron las imagenes a almacenar en el nuevo ContenedorImagenes
Definition at line 20 of file main.cpp.
References VDinamico< T >::borrar(), VDinamico< T >::insertar(), and VDinamico< T >::tamlog().
Referenced by main().